EventDate:
  type: "object"
  config:
    fields:
      start: { type: "DateTime!" }
      end: { type: "DateTime" }
      rrule: { type: "String" }
      isFullDay: { type: "Boolean!" }
      hasStartTime: { type: "Boolean!" }
      hasEndTime: { type: "Boolean!" }