services:
  _defaults:
    autowire: true
    autoconfigure: true
  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  Atoolo\EventsCalendar\Console\:
    resource: '../src/Console'

  Atoolo\EventsCalendar\Console\Application:
    public: true
    arguments:
      - !tagged command

  Atoolo\Search\Console\Command\Io\IndexerProgressBarFactory:
    ~

  atoolo.resource.cachedResourceLoader:
    class: Atoolo\Resource\Loader\CachedResourceLoader
    arguments:
      - '@atoolo.resource.resourceLoader'

  atoolo.resource.categoryHierarchyLoader:
    class: Atoolo\Resource\Loader\SiteKitResourceHierarchyLoader
    arguments:
      - "@atoolo.resource.cachedResourceLoader"
      - "category"

  Atoolo\EventsCalendar\Service\Indexer\SiteKit\DefaultSchema2xRceEventDocumentEnricher:
    arguments:
      - '@atoolo.resource.categoryHierarchyLoader'
      - '@atoolo.search.indexer.contentCollector.sitekit'
    tags:
      - { name: 'atoolo.eventsCalendar.indexer.rceEventDocumentEnricher.schema2x', priority: 100 }

  atoolo.eventsCalendar.indexer.rceEventAborter:
    class: Atoolo\Search\Service\Indexer\IndexingAborter
    arguments:
      - '%kernel.project_dir%/var/cache/'
      - 'rce-event'

  Atoolo\EventsCalendar\Service\RceEvent\RceEventListHttpClient: ~

  Atoolo\EventsCalendar\Service\RceEvent\RceEventListItemFactory: ~

  Atoolo\EventsCalendar\Service\RceEvent\RceEventListReader:
    arguments:
      - '%kernel.project_dir%/var/cache/'
      - '@Atoolo\EventsCalendar\Service\RceEvent\RceEventListHttpClient'
      - '@Atoolo\EventsCalendar\Service\RceEvent\RceEventListItemFactory'

  atoolo.eventsCalendar.indexer.progressState:
    class: Atoolo\Search\Service\Indexer\IndexerProgressState
    arguments:
      - '@atoolo.search.indexName'
      - '@atoolo.search.indexer.statusStore'
      - 'rce-event'

  Atoolo\EventsCalendar\Service\Indexer\RceEventIndexer:
    arguments:
      - !tagged_iterator { tag: 'atoolo.eventsCalendar.indexer.rceEventDocumentEnricher.schema2x' }
      - '@atoolo.eventsCalendar.indexer.progressState'
      - '@atoolo.eventsCalendar.indexer.rceEventAborter'
      - '@Atoolo\EventsCalendar\Service\RceEvent\RceEventListReader'
      - '@atoolo.search.indexer.solrIndexService'
      - '@atoolo.search.indexName'
      - '@atoolo.search.indexer.configurationLoader'
      - 'rce-event'
    tags:
      - { name: 'atoolo.search.indexer', priority: 10 }

  Atoolo\EventsCalendar\Service\Indexer\RceEventIndexerScheduler:
    arguments:
      - '0 6-20/2 * * *' # cron expression, every 2 hours from 6am to 8pm

  Atoolo\EventsCalendar\Service\Indexer\StopWorkerOnRedeployListener:
    arguments:
      - '%kernel.cache_dir%'

  Atoolo\EventsCalendar\Console\Command\RceEventIndexerCommand:
    arguments:
      - '@atoolo.search.indexer.console.progressBar'
      - '@Atoolo\EventsCalendar\Service\Indexer\RceEventIndexer'
