services:
  _defaults:
    autowire: true
    autoconfigure: true

  Atoolo\EventsCalendar\Service\Indexer\SiteKit\DefaultSchema2xRceEventDocumentEnricher:
    arguments:
      - '@atoolo_resource.category_hierarchy_loader'
      - '@atoolo_search.indexer.content_collector.sitekit'
    tags:
      - { name: 'atoolo.eventsCalendar.indexer.rceEventDocumentEnricher.schema2x', priority: 100 }

  atoolo.eventsCalendar.indexer.rceEventAborter:
    class: Atoolo\Search\Service\Indexer\IndexingAborter
    arguments:
      - '%kernel.project_dir%/var/cache/'
      - 'rce-event'

  Atoolo\EventsCalendar\Service\RceEvent\RceEventListHttpClient: ~

  Atoolo\EventsCalendar\Service\RceEvent\RceEventListItemFactory: ~

  Atoolo\EventsCalendar\Service\RceEvent\RceEventListReader:
    arguments:
      - '%kernel.project_dir%/var/cache/'
      - '@Atoolo\EventsCalendar\Service\RceEvent\RceEventListHttpClient'
      - '@Atoolo\EventsCalendar\Service\RceEvent\RceEventListItemFactory'

  atoolo.eventsCalendar.indexer.progressState:
    class: Atoolo\Search\Service\Indexer\IndexerProgressState
    arguments:
      - '@atoolo_search.index_name'
      - '@atoolo_search.indexer.status_store'
      - 'rce-event'

  Atoolo\EventsCalendar\Service\Indexer\RceEventIndexer:
    arguments:
      - !tagged_iterator { tag: 'atoolo.eventsCalendar.indexer.rceEventDocumentEnricher.schema2x' }
      - '@atoolo.eventsCalendar.indexer.progressState'
      - '@atoolo.eventsCalendar.indexer.rceEventAborter'
      - '@Atoolo\EventsCalendar\Service\RceEvent\RceEventListReader'
      - '@atoolo_search.indexer.solr_index_service'
      - '@atoolo_search.index_name'
      - '@atoolo_search.indexer.configuration_loader'
      - 'rce-event'
    tags:
      - { name: 'atoolo_search.indexer', priority: 10 }

  Atoolo\EventsCalendar\Service\Indexer\RceEventIndexerScheduler:
    arguments:
      - '0 6-20/2 * * *' # cron expression, every 2 hours from 6am to 8pm

  Atoolo\EventsCalendar\Service\Indexer\StopWorkerOnRedeployListener:
    arguments:
      - '%kernel.cache_dir%'

  Atoolo\EventsCalendar\Console\Command\RceEventIndexerCommand:
    arguments:
      - '@atoolo_search.indexer.console.progress_bar'
      - '@Atoolo\EventsCalendar\Service\Indexer\RceEventIndexer'
