EventTeaserDecorator:
  type: object
  decorator: true
  inherits: [Teaser]
  config:
    interfaces: [Teaser]
    description: Event teaser
    fields:
      headline:
        type: "String"
        description: Teaser headline
      text:
        type: "String"
        description: Teaser text
      kicker:
        type: "String"
        description: Teaser kicker text
      asset:
        type: "Asset"
        args:
          variant:
            type: "String!"
            description: The teaser variant is used to decide which image format is to be returned.
        description: Teaser asset can be e.g. pictures or videos
      symbolicImage:
        type: "SymbolicImage"
        description: symbolic image associated with the teaser
      schedulings:
        type: "[Scheduling!]!"
        description: schedulings